### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by grex-gh** [GoogleCloudPlatform/terraform-google-secret-manager#44]
Do you plan to support this module or can we assume it's development is dead?

**Comment by sakomws** [comment]
It requires Google provider version below 5. Can we bump it to support latest one?

**Comment by grex-gh** [comment]
There was an [PR](https://github.com/GoogleCloudPlatform/terraform-google-secret-manager/pull/32) for this but never got merged

**Comment by apeabody** [comment]
Hi Everyone - The just released [v0.2.0](https://github.com/GoogleCloudPlatform/terraform-google-secret-manager/releases/tag/v0.2.0) adds support for TPG v5.
